### ISSUE TITLE
fasten the analysis

### ISSUE THREAD

**Issue by shokohirosue** [UcarLab/BiFET#4]
Hi,

Thank you for developing/maintaining a great package!

Do you think it makes sense to filter the PIQ output by the peak regions to fasten the analysis, or it would make no sense?

Thank you so much for your help.

Best,
Shoko

**Comment by nlawlor** [comment]
Hi Shoko,

Thank you again for your interest in our method! The `calculate_enrich_p ` function works by determining which footprint calls of a TF overlap the target peak set region (and also those footprint calls that do **not** overlap the peaks) and then performs a hypergeometric test to assess whether there is over-representation. I don't advise filtering the PIQ output by peak regions because that would bias the enrichment analysis. @youna2 please chime in if I missed anything :)

Best,
Nathan

**Comment by youna2** [comment]
I think it makes sense to filter the PIQ output by the peak regions as long as the peak regions include target regions and background regions. BiFET identifies TFs whose footprints are over-represented in target peak regions compared to background peak regions and therefore, it only focuses on footprints that overlap target and background peak regions.

**Comment by shokohirosue** [comment]
Thank you both so much. 

May I ask you one more question?
It is a question re. use of package `DiffBind` use in your tutorial, so not directly relevant to your package, but I would be grateful if you could help me out.

I have been trying to follow[ the tutorial](https://bioconductor.org/packages/release/bioc/vignettes/BiFET/inst/doc/BiFET.html). I understand you processed the peaks as follows:
1) generate one consensus peak set by using R package DiffBind_2.2.5. where only the peaks present at least in any two samples were included in the analysis, using the summits option to re-center each peak around the point of greatest enrichment and obtained consensus peaks of same width (200bp).
2) define regions that are specifically accessible in PBMC samples as regions where at least 4 PBMC samples have a peak, whereas none of the islet samples have a peak
3) Similarly, define islet-specific peaks as those that were called as a peak in at least 4 islet samples but none in any of the PBMC samples.

I was trying to follow these steps using DiffBind  `dba.count` and `dba.peakset` functions. However, when I run `dba.count` with arguments` summits=100` and `minOverlap=2`, it only retains the consensus list in the object and does not allow me to identify regions that are treatment/control specific. 

May I ask you what packages/methods you used to achieve 2) and 3)?

I am sorry for the trouble. Thank you so much for your help.

Best,
Shoko

**Comment by nlawlor** [comment]
You're very welcome, Shoko! We are both happy to help in anyway that we can :)

There are actually a number of ways that you can use to find regions that are treatment/control specific. But here's an option I would suggest:

After defining your consensus peak set with DiffBind and your above arguments, you can determine treatment specific peaks by performing a differential peak analysis using the `dba.analyze` function within the DiffBind package and specify your contrasts variable (DBA$contrast) as your treatment/control variable and DBA_EDGER or DBA_DESEQ2 as the differential analysis method. 

I hope this helps!
Nathan

**Comment by nlawlor** [comment]
Closing this issue for now, Shoko. If you need any further clarification, please re-open the issue and let us know :)
