### ISSUE TITLE
alpha_k value

### ISSUE THREAD

**Issue by shokohirosue** [UcarLab/BiFET#5]
Hi,

Would you mind telling me how I could interpret alpha_k value of the output?

Thank you so much for your help.

Best,
Shoko

**Comment by nlawlor** [comment]
Hi Shoko,

Thanks for your interest in BiFet! I've referenced @youna2 (the creator of the algorithm) for her expertise on this. In the meantime, hopefully this excerpt (regarding the alpha_k parameter) from the associated manuscript `https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6344870/` can help:

![image](https://user-images.githubusercontent.com/16104148/76028635-06af9e00-5f01-11ea-9807-ff01a79d3782.png)

**Comment by youna2** [comment]
Thank you Nathan for your answer. As written in the paragraph, alpha_k is the rate that determines how fast f_1 converges to 1 as the number of reads increases. With large alpha_k, f_1 converges to 1 faster.

**Comment by youna2** [comment]
Thank you Nathan for your answer. As written in the paragraph, alpha_k is the rate that determines how fast f_1 converges to 1 as the number of reads increases. With large alpha_k, f_1 converges to 1 faster.

**Comment by shokohirosue** [comment]
Hi,

Thank you very much for your reply! 
For now, I have been filtering the output based on p.bifet column (I am ignoring p.hyper and alpha.k column) and using the resulting TF list as a non-ranked list for further downstream analyis.

Would you recommend any other/better way of result interpretation? Would it be possible to rank the list of TFs in any ways?

Thank you so much.

Best,
Shoko

**Comment by nlawlor** [comment]
Hi Shoko,

I think the way you are filtering the output makes sense if you are trying to find the most over-represented TF footprints in your target peak-set. 

You can also filter your TF list based on the confidence of footprint detection from your PIQ output (e.g., for PIQ it provides a value of confidence; positive predictive values (PPV)). In our manuscript we only considered TF footprints with PPV > 0.9.

Best,
Nathan

**Comment by nlawlor** [comment]
Closing this issue for now, Shoko. If you need any further clarification, please re-open the issue and let us know :)
